### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by rohan-varma** [Austin-lee0/Autoregressive-and-Moving-Average-Model-Homework#1]
Hi,

I came across this repository while doing homework for my economics class. The problem is, none of this code works. Could you please upload something that is even remotely working?

Thanks,
Rohan

**Comment by Austin-lee0** [comment]
Hey Rohan!

Have you downloaded RStudio? I'm sure all of the code works properly; have you looked at the Rmarkdown PDF?
